### ISSUE TITLE
Client Crashes When Other Player Talks

### ISSUE THREAD

**Issue by IAmSneak** [henkelmax/simple-voice-chat#163]
Client crashes when player around them starts talking with the player that is muted or not talking. This doesn't happen every time. According to the other players on my server, it usually happens after talking for a few mins and its in pauses.

**Steps to reproduce the issue**
1. Talk to someone to a little while while they have the mod active (either muted, not talking, or talking).
2. Have a brief break from talking to them (15 seconds maybe).
3. Sometimes crashes (inconsistently)

**Expected behavior**
Talks without crashing

**Log files**
[2021-04-22-7.log.gz](https://github.com/henkelmax/simple-voice-chat/files/6362482/2021-04-22-7.log.gz)

**Versions**
- 1.16.4
- Fabric loader 0.11.3
- Fabric Api 0.32.5
- Voicechat 1.1.5

**Other mods**
Many mods are being used but here are ones that have a chance of causing the issue:
carpet mod
krypton
lithium
sodium
starlight

    **Config**
port=24454
bind_address=0.0.0.0
sample_rate=16000
voice_fade_distance=24.0
voice_distance=64.0
codec=VOIP
keep_alive=1000
mtu_size=900

**Comment by henkelmax** [comment]
Does this also happen without any other mods?
There are a lot of OpenGL errors in your logs. I'm assuming, that they are not caused by the voice chat.

**Comment by Alkiasan** [comment]
Having the same issue as a random crash. Also running Carpet, Krypton, and Lithium, but not Sodium/starlight.
Crash seems to be relating to this particular part of the log:
[04:09:40] [AudioChannelThread-ba361218-7dd8-4bc0-9bfb-576c6aece479/INFO]: [STDERR]: java.lang.Error: Invalid memory access
[04:09:40] [AudioChannelThread-ba361218-7dd8-4bc0-9bfb-576c6aece479/INFO]: [STDERR]: 	at com.sun.jna.Native.invokeInt(Native Method)
[04:09:40] [AudioChannelThread-ba361218-7dd8-4bc0-9bfb-576c6aece479/INFO]: [STDERR]: 	at com.sun.jna.Function.invoke(Function.java:426)
[04:09:40] [AudioChannelThread-ba361218-7dd8-4bc0-9bfb-576c6aece479/INFO]: [STDERR]: 	at com.sun.jna.Function.invoke(Function.java:361)
[04:09:40] [AudioChannelThread-ba361218-7dd8-4bc0-9bfb-576c6aece479/INFO]: [STDERR]: 	at com.sun.jna.Library$Handler.invoke(Library.java:265)
[04:09:40] [AudioChannelThread-ba361218-7dd8-4bc0-9bfb-576c6aece479/INFO]: [STDERR]: 	at com.sun.proxy.$Proxy88.opus_decode(Unknown Source)
[04:09:40] [AudioChannelThread-ba361218-7dd8-4bc0-9bfb-576c6aece479/INFO]: [STDERR]: 	at de.maxhenkel.voicechat.voice.common.OpusDecoder.decode(OpusDecoder.java:36)
[04:09:40] [AudioChannelThread-ba361218-7dd8-4bc0-9bfb-576c6aece479/INFO]: [STDERR]: 	at de.maxhenkel.voicechat.voice.client.AudioChannel.run(AudioChannel.java:142)

**Comment by henkelmax** [comment]
Please try if it happens without these mods.

**Comment by IAmSneak** [comment]
It is quite hard to consistently reproduce. I am able to confirm it can crash with just carpet, lithium, and krypton on the server.

**Comment by henkelmax** [comment]
Can you narrow down the mod to a single mod?

**Comment by Alkiasan** [comment]
Krypton's optimisations focus on the net stack. It might be worth checking to see if any of the optimisations krypton makes would effect the voice chat mod?

**Comment by henkelmax** [comment]
It should not affect it, since the voicechat mod does not use minecrafts networking.

**Comment by Alkiasan** [comment]
Actually, come to think of it, the crash is a clientside crash, so it would be weird if these serverside mods are causing it, since I don't have them installed clientside...

**Comment by Alkiasan** [comment]
IAmSneak, What clientside mods do you have installed?
Maybe we can compare and look at the similarities?

**Comment by henkelmax** [comment]
@IAmSneak @Alkiasan Please try the latest version of the mod. I fixed another bug and it might be related to this.

**Comment by Alkiasan** [comment]
Installed the latest version on server and client, sadly, issue still persists.

**Comment by henkelmax** [comment]
Alright, thank you for testing it

**Comment by Alkiasan** [comment]
no error this time. Final line was 
[03:20:49] [VoiceChatClientThread/INFO]: Initializing Opus decoder with sample rate 48000 Hz, frame size 1920 bytes and max payload size 1024 bytes
Log cuts off there.
No crash log generated.

**Comment by henkelmax** [comment]
Great, does this mean it works now?

**Comment by Alkiasan** [comment]
No, the error just doesn't appear in the log anymore. The crash still
happens.

**Comment by henkelmax** [comment]
If it crashes, it has to be in the logs, please send me the logs.

**Comment by Alkiasan** [comment]
[2021-04-30-3.log](https://github.com/henkelmax/simple-voice-chat/files/6409989/2021-04-30-3.log)

**Comment by Alkiasan** [comment]
From the logs folder.
A crash log isn't generated.
This isn't edited. Scroll down and you'll see it just stops.

**Comment by henkelmax** [comment]
Yes, but I can assume what causes it, with the last log entry.

What OS are you using?

**Comment by Alkiasan** [comment]
Windows 10

**Comment by henkelmax** [comment]
It would be nice if you could narrow down the mods you are using. If I know which mod is causing it I can reproduce it.

**Comment by Alkiasan** [comment]
It's already been narrowed down to three by IAmSneak, and judging from what you said, it can't be Krypton, So it's either Lithium or Carpet causing it.

**Comment by henkelmax** [comment]
Ok, then just test it which mod exactly causes it.

**Comment by henkelmax** [comment]
Any update on this?

**Comment by crash-ip21** [comment]
Can confirm the issue, experiencing random crashes when talking to another person in a group.
Experienced latest.log sadly doesn't have information about crash.
There are few last lines:
```
[20:18:06] [VoiceChatClientThread/INFO]: Initializing Opus decoder with sample rate 48000 Hz, frame size 1920 bytes and max payload size 1024 bytes
[20:20:03] [main/INFO]: [CHAT] [Debug]: Hitboxes: hidden
[20:24:00] [main/WARN]: Block entity invalid: minecraft:chest @ class_2338{x=712, y=137, z=-1199}
[20:24:08] [main/WARN]: Block entity invalid: minecraft:chest @ class_2338{x=714, y=137, z=-1201}
[20:26:53] [main/WARN]: Block entity invalid: minecraft:chest @ class_2338{x=706, y=93, z=-1204}
[20:26:58] [main/WARN]: Block entity invalid: minecraft:ender_chest @ class_2338{x=706, y=93, z=-1205}
[20:29:40] [VoiceChatClientThread/INFO]: Initializing Opus decoder with sample rate 48000 Hz, frame size 1920 bytes and max payload size 1024 bytes
[20:30:01] [main/INFO]: [CHAT] [Server: Saved the game]
[20:30:38] [main/INFO]: [CHAT] [Debug]: Hitboxes: shown
```

Crash happened at ~20:31

P. S. Game exited with code 0, so there's nothing in `crash-reports` either.

![image](https://user-images.githubusercontent.com/60033634/117473866-da176c00-af73-11eb-8895-337569b18bb0.png)

**Comment by henkelmax** [comment]
Does this happen with the latest version of the mod?
Which modloader are you using?

**Comment by crash-ip21** [comment]
> Does this happen with the latest version of the mod?
> Which modloader are you using?

Version 1.3.7 both on the server and client, Fabric.

**Comment by crash-ip21** [comment]
> Do you use any of the aforementioned mods?
> 
> It will be hard to reproduce this issue, since the crash happens randomly and produces no logs...

Server uses carpet, lithium, hydrogen.

On client from mentioned mods are sodium and carpet as well.

If there's a way to talk to you privately, like in Discord dms, I could give you full list of mods both on server and client.

> Please let me know if you find out when exactly the crash happens.

They kinda happen randomly, but I only noticed them happening in groups. My friend got crashes too, he's got sodium, but doesn't have carpet on his client.

**Comment by henkelmax** [comment]
Yeah, it's fine, a friend of me got the crashes as well on Forge with completely different mods...

**Comment by henkelmax** [comment]
It should be fixed with the latest version (1.3.10 with Fabric and 1.3.8 with Forge)

**Comment by crash-ip21** [comment]
@henkelmax thank you very much for fixing this bug this fast! We really like this mod with my friends and appreciate how fast you resolved the issue, even though it wasn't an obvious one!

**Comment by henkelmax** [comment]
> @henkelmax thank you very much for fixing this bug this fast! We really like this mod with my friends and appreciate how fast you resolved the issue, even though it wasn't an obvious one!

No problem :)
Let me know if it works for you.

**Comment by crash-ip21** [comment]
We will give it a test today!

**Comment by crash-ip21** [comment]
@henkelmax 
Okay, sorry didn't got back to you earlier. We've been playing with the version 1.3.10 since it was released, and didn't have any crashes! Thanks again for fixing an issue

**Comment by henkelmax** [comment]
No problem :)
